name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
  publish:
    runs-on: ubuntu-latest
    needs: [ verify ]
    steps:
      - uses: actions/checkout@v4
      - name: setup java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: graalvm
          cache: 'gradle'
      - name: Validate version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if grep -Eq "version\s+=\s+\"${VERSION}\"" ./build.gradle.kts
          then
            echo "Publishing version '${VERSION}'"
            ./gradlew publish
          else
            echo "Detected tag version '${VERSION}' and version from build.gradle.kts does not match."
            exit 1
          fi
      - name: Publish
        run: ./gradlew publishToCentralPortal
        env:
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          SIGNING_SECRETKEY: ${{ secrets.SIGNING_SECRETKEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          LIBRARY_GROUP: ${{ vars.LIBRARY_GROUP }}
          SIGNING_KEYID: ${{ vars.SIGNING_KEYID }}